### ISSUE TITLE
Enforce consistent style rules

### ISSUE THREAD

**Issue by ob-stripe** [stripe/stripe-java#476]
This is going to be done over several PRs, so I'm using this issue to track progress.

- [x] Use checkstyle with Google checks (#475)
- [x] Use 2 spaces instead of tabs for indentation (#477)
- [x] Fix import order and * imports (#478) 
- [x] Limit line length to 100 characters (#479)
- [x] Fix more linting errors (#480)
- [x] Rule for consecutive capital letters (#481)
- [x] Fix distance linting issues (#482)
- [x] Group overload methods (#483)
- [x] Fix Javadoc comments (#484)
- [x] Fix variable and method names (#485)
- [x] Fix linting issue about having multiple top-level classes in same file (#486)
- [x] Fix missing Javadoc linting issues (#487)
- [x] Enforce no checkstyle issues during build (#489)

**Comment by ob-stripe** [comment]
Phew! We're done for now. Closing this out.
